services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PUBLIC_BASE_PATH=http://host.docker.internal:9000
