import { describe, expect, it } from 'vitest';

import {
	getGaussianSplatRenderBounds,
	inspectGaussianSplatPly,
	parseGaussianSplatPly
} from './index';

const gaussianProperties = [
	'x',
	'y',
	'z',
	'f_dc_0',
	'f_dc_1',
	'f_dc_2',
	'opacity',
	'scale_0',
	'scale_1',
	'scale_2',
	'rot_0',
	'rot_1',
	'rot_2',
	'rot_3'
];

const createSyntheticGaussianPly = () => {
	const header = [
		'ply',
		'format binary_little_endian 1.0',
		'element vertex 2',
		...gaussianProperties.map((name) => `property float ${name}`),
		'end_header',
		''
	].join('\n');
	const headerBytes = new TextEncoder().encode(header);
	const buffer = new ArrayBuffer(headerBytes.length + gaussianProperties.length * 4 * 2);
	new Uint8Array(buffer, 0, headerBytes.length).set(headerBytes);
	const view = new DataView(buffer);
	const vertices = [
		[2, 1, -3, 0, 0, 0, 0, Math.log(2), Math.log(1), Math.log(0.5), 1, 0, 0, 0],
		[8, 5, 4, 1, -1, 0.5, Math.log(3), Math.log(1), Math.log(1), Math.log(1), 1, 0, 0, 0]
	];
	vertices.forEach((vertex, vertexIndex) => {
		vertex.forEach((value, propertyIndex) => {
			view.setFloat32(
				headerBytes.length + (vertexIndex * gaussianProperties.length + propertyIndex) * 4,
				value,
				true
			);
		});
	});
	return buffer;
};

describe('3D Gaussian Splatting PLY', () => {
	it('通常PLYの属性を判定して展開する', () => {
		const buffer = createSyntheticGaussianPly();

		expect(inspectGaussianSplatPly(buffer)).toEqual({
			kind: 'gaussian-splat',
			splatCount: 2,
			shDegree: 0
		});

		const data = parseGaussianSplatPly(buffer);
		expect(Array.from(data.positions)).toEqual([2, 1, -3, 8, 5, 4]);
		expect(Array.from(data.bounds)).toEqual([2, 1, -3, 8, 5, 4]);
		expect(getGaussianSplatRenderBounds(data.bounds)).toEqual([2, 0, -3, 8, 4, 4]);
		expect(data.opacities[0]).toBeCloseTo(0.5);
		expect(data.opacities[1]).toBeCloseTo(0.75);
		expect(data.scales[0]).toBeCloseTo(2);
		expect(data.colors[0]).toBe(128);
	});

	it('SuperSplat圧縮PLYを通常PLYとして扱わない', () => {
		const header = [
			'ply',
			'format binary_little_endian 1.0',
			'comment Generated by SuperSplat',
			'element vertex 1',
			'property uint packed_position',
			'end_header',
			''
		].join('\n');

		expect(inspectGaussianSplatPly(new TextEncoder().encode(header).buffer)).toEqual({
			kind: 'super-splat',
			reason: 'SuperSplat の圧縮 PLY は通常 PLY の属性配置と異なります'
		});
	});
});
