const HEADER_SEARCH_LIMIT = 128 * 1024;
const SH_C0 = 0.28209479177387814;

type PlyScalarType =
	| 'char'
	| 'uchar'
	| 'short'
	| 'ushort'
	| 'int'
	| 'uint'
	| 'float'
	| 'double';

interface PlyProperty {
	name: string;
	type: PlyScalarType;
	offset: number;
}

interface ParsedPlyHeader {
	vertexCount: number;
	dataOffset: number;
	stride: number;
	properties: PlyProperty[];
	propertyNames: Set<string>;
	comments: string[];
}

export type GaussianSplatPlyInspection =
	| { kind: 'gaussian-splat'; splatCount: number; shDegree: number; }
	| { kind: 'super-splat'; reason: string; }
	| { kind: 'other-ply'; };

export interface GaussianSplatData {
	positions: Float32Array;
	colors: Uint8Array;
	opacities: Float32Array;
	scales: Float32Array;
	bounds: [number, number, number, number, number, number];
}

export class GaussianSplatPlyError extends Error {}

const SCALAR_BYTE_SIZES: Record<PlyScalarType, number> = {
	char: 1,
	uchar: 1,
	short: 2,
	ushort: 2,
	int: 4,
	uint: 4,
	float: 4,
	double: 8
};

const REQUIRED_GAUSSIAN_PROPERTIES = [
	'x',
	'y',
	'z',
	'f_dc_0',
	'f_dc_1',
	'f_dc_2',
	'opacity',
	'scale_0',
	'scale_1',
	'scale_2',
	'rot_0',
	'rot_1',
	'rot_2',
	'rot_3'
];

const decodeHeaderText = (buffer: ArrayBuffer) => {
	const bytes = new Uint8Array(buffer, 0, Math.min(buffer.byteLength, HEADER_SEARCH_LIMIT));
	return new TextDecoder('ascii').decode(bytes);
};

const findHeaderEnd = (text: string) => {
	const lfEnd = text.indexOf('end_header\n');
	if (lfEnd >= 0) return lfEnd + 'end_header\n'.length;
	const crlfEnd = text.indexOf('end_header\r\n');
	return crlfEnd >= 0 ? crlfEnd + 'end_header\r\n'.length : -1;
};

const parsePlyHeader = (buffer: ArrayBuffer): ParsedPlyHeader | null => {
	const text = decodeHeaderText(buffer);
	const dataOffset = findHeaderEnd(text);
	if (dataOffset < 0) return null;

	const headerText = text.slice(0, dataOffset);
	const lines = headerText.split(/\r?\n/);
	if (lines[0] !== 'ply' || !lines.includes('format binary_little_endian 1.0')) return null;

	let vertexCount = 0;
	let inVertexElement = false;
	let stride = 0;
	const properties: PlyProperty[] = [];
	const comments: string[] = [];

	for (const line of lines) {
		if (line.startsWith('comment ')) {
			comments.push(line.slice('comment '.length));
			continue;
		}
		if (line.startsWith('element ')) {
			const [, elementName, countText] = line.split(/\s+/);
			inVertexElement = elementName === 'vertex';
			if (inVertexElement) vertexCount = Number(countText);
			continue;
		}
		if (!inVertexElement || !line.startsWith('property ')) continue;

		const [, type, name] = line.split(/\s+/) as [string, PlyScalarType, string];
		if (!(type in SCALAR_BYTE_SIZES) || !name) {
			return null;
		}
		properties.push({ name, type, offset: stride });
		stride += SCALAR_BYTE_SIZES[type];
	}

	if (!Number.isSafeInteger(vertexCount) || vertexCount <= 0 || stride <= 0) return null;
	return {
		vertexCount,
		dataOffset,
		stride,
		properties,
		propertyNames: new Set(properties.map((property) => property.name)),
		comments
	};
};

const getShDegree = (propertyNames: Set<string>) => {
	const restCount = Array.from(propertyNames).filter((name) => /^f_rest_\d+$/.test(name)).length;
	const degree = Math.sqrt(restCount / 3 + 1) - 1;
	return Number.isInteger(degree) && degree >= 0 ? degree : 0;
};

const isSuperSplatHeader = (header: ParsedPlyHeader, text: string) => {
	return (
		header.propertyNames.has('packed_position') ||
		header.comments.some((comment) => /supersplat/i.test(comment)) ||
		/generated by supersplat/i.test(text)
	);
};

export const inspectGaussianSplatPly = (buffer: ArrayBuffer): GaussianSplatPlyInspection => {
	const header = parsePlyHeader(buffer);
	if (!header) return { kind: 'other-ply' };
	const headerText = decodeHeaderText(buffer);
	if (isSuperSplatHeader(header, headerText)) {
		return {
			kind: 'super-splat',
			reason: 'SuperSplat の圧縮 PLY は通常 PLY の属性配置と異なります'
		};
	}
	if (!REQUIRED_GAUSSIAN_PROPERTIES.every((name) => header.propertyNames.has(name))) {
		return { kind: 'other-ply' };
	}
	return {
		kind: 'gaussian-splat',
		splatCount: header.vertexCount,
		shDegree: getShDegree(header.propertyNames)
	};
};

export const inspectGaussianSplatPlyFile = async (file: File) => {
	return inspectGaussianSplatPly(await file.slice(0, HEADER_SEARCH_LIMIT).arrayBuffer());
};

const getNumber = (view: DataView, offset: number, type: PlyScalarType) => {
	switch (type) {
		case 'char': return view.getInt8(offset);
		case 'uchar': return view.getUint8(offset);
		case 'short': return view.getInt16(offset, true);
		case 'ushort': return view.getUint16(offset, true);
		case 'int': return view.getInt32(offset, true);
		case 'uint': return view.getUint32(offset, true);
		case 'float': return view.getFloat32(offset, true);
		case 'double': return view.getFloat64(offset, true);
	}
};

const sigmoid = (value: number) => 1 / (1 + Math.exp(-value));
const toColorChannel = (value: number) => Math.round(Math.max(0, Math.min(1, value)) * 255);

export const parseGaussianSplatPly = (buffer: ArrayBuffer): GaussianSplatData => {
	const inspection = inspectGaussianSplatPly(buffer);
	if (inspection.kind === 'super-splat') {
		throw new GaussianSplatPlyError(
			'SuperSplat 圧縮 PLY は未対応です。通常 PLY に書き出して読み込んでください。'
		);
	}
	if (inspection.kind !== 'gaussian-splat') {
		throw new GaussianSplatPlyError('3D Gaussian Splatting の通常 PLY 属性が見つかりません。');
	}

	const header = parsePlyHeader(buffer);
	if (!header) throw new GaussianSplatPlyError('PLYヘッダーを読み取れませんでした。');
	const requiredBytes = header.dataOffset + header.vertexCount * header.stride;
	if (requiredBytes > buffer.byteLength) {
		throw new GaussianSplatPlyError('PLYの頂点データが途中で終わっています。');
	}

	const properties = new Map(header.properties.map((property) => [property.name, property]));
	const property = (name: string) => {
		const value = properties.get(name);
		if (!value) throw new GaussianSplatPlyError(`PLY属性 ${name} が見つかりません。`);
		return value;
	};
	const x = property('x');
	const y = property('y');
	const z = property('z');
	const dc0 = property('f_dc_0');
	const dc1 = property('f_dc_1');
	const dc2 = property('f_dc_2');
	const opacity = property('opacity');
	const scales = [property('scale_0'), property('scale_1'), property('scale_2')];
	const view = new DataView(buffer);
	const positions = new Float32Array(header.vertexCount * 3);
	const colors = new Uint8Array(header.vertexCount * 3);
	const opacities = new Float32Array(header.vertexCount);
	const radii = new Float32Array(header.vertexCount);
	let minX = Infinity;
	let minY = Infinity;
	let minZ = Infinity;
	let maxX = -Infinity;
	let maxY = -Infinity;
	let maxZ = -Infinity;

	for (let index = 0; index < header.vertexCount; index += 1) {
		const offset = header.dataOffset + index * header.stride;
		const positionX = getNumber(view, offset + x.offset, x.type);
		const positionY = getNumber(view, offset + y.offset, y.type);
		const positionZ = getNumber(view, offset + z.offset, z.type);
		if (![positionX, positionY, positionZ].every(Number.isFinite)) {
			throw new GaussianSplatPlyError('PLYに有限でない座標値が含まれています。');
		}
		const itemOffset = index * 3;
		positions[itemOffset] = positionX;
		positions[itemOffset + 1] = positionY;
		positions[itemOffset + 2] = positionZ;
		colors[itemOffset] = toColorChannel(0.5 + SH_C0 * getNumber(view, offset + dc0.offset, dc0.type));
		colors[itemOffset + 1] = toColorChannel(0.5 + SH_C0 * getNumber(view, offset + dc1.offset, dc1.type));
		colors[itemOffset + 2] = toColorChannel(0.5 + SH_C0 * getNumber(view, offset + dc2.offset, dc2.type));
		opacities[index] = sigmoid(getNumber(view, offset + opacity.offset, opacity.type));
		const maxLogScale = Math.max(
			...scales.map((scale) => getNumber(view, offset + scale.offset, scale.type))
		);
		radii[index] = Math.exp(Math.max(-20, Math.min(20, maxLogScale)));
		minX = Math.min(minX, positionX);
		minY = Math.min(minY, positionY);
		minZ = Math.min(minZ, positionZ);
		maxX = Math.max(maxX, positionX);
		maxY = Math.max(maxY, positionY);
		maxZ = Math.max(maxZ, positionZ);
	}

	return {
		positions,
		colors,
		opacities,
		scales: radii,
		bounds: [minX, minY, minZ, maxX, maxY, maxZ]
	};
};
